eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8083
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            -   id: customer
                predicates:
                - Path=/api/customers/**
                uri: lb://CUSTOMER
    zipkin:
        base-url: http://localhost:9411
