eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
server:
    port: 8081
spring:
    application:
        name: fraud
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/fraud
        username: abbas
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show_sql: true
    zipkin:
        base-url: http://localhost:9411
